### ISSUE TITLE
yarn build error!

### ISSUE THREAD

**Issue by pmc1388** [devowlio/wp-react-starter#27]
Hi again.
This errors show in the build action:

Starting type checking service...

✖ Wp-reactjs-starter
  Compiled with some errors in 10.23s

[WEBPACK] Build failed after 17.819 seconds
[WEBPACK] Errors building [name].js
ERROR in ../wp-react-starter--wp-reactjs-multi-starter-wp-reactjs-starter-1.2.0/plugins/wp-reactjs-starter/src/public/ts/store/stores.tsx(29,16):
TS2742: The inferred type of 'context' cannot be named without a reference to '@wp-reactjs-multi-starter/utils/node_modules/@types/react'. This is likely not portable. A type annotation is necessary.
ERROR in ../wp-react-starter--wp-reactjs-multi-starter-wp-reactjs-starter-1.2.0/plugins/wp-reactjs-starter/src/public/ts/store/stores.tsx(40,23):
TS2742: The inferred type of 'StoreProvider' cannot be named without a reference to '@wp-reactjs-multi-starter/utils/node_modules/@types/react'. This is likely not portable. A type annotation is necessary.
ERROR in ..wp-react-starter--wp-reactjs-multi-starter-wp-reactjs-starter-1.2.0/plugins/wp-reactjs-starter/src/public/ts/utils/index.tsx(21,16):
TS2742: The inferred type of 'localization' cannot be named without a reference to '@wp-reactjs-multi-starter/utils/node_modules/@types/react'. This is likely n
✔ Utils
  Compiled successfully in 11.18s

[WEBPACK] Finished building index.js within 11.18 seconds
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:679:16)
    at callback (../wp-react-starter--wp-reactjs-multi-starter-wp-reactjs-starter-1.2.0/node_modules/worker-farm/lib/child/index.js:32:17)
    at finishedCallback (../wp-react-starter--wp-reactjs-multi-starter-wp-reactjs-starter-1.2.0/node_modules/parallel-webpack/src/webpackWorker.js:141:21)
    at finalCallback (../wp-react-starter--wp-reactjs-multi-starter-wp-reactjs-starter-1.2.0/node_modules/webpack/lib/Compiler.js:257:39)
    at ../wp-react-starter--wp-reactjs-multi-starter-wp-reactjs-starter-1.2.0/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (../wp-react-starter--wp-reactjs-multi-starter-wp-reactjs-starter-1.2.0/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:40:1)
    at AsyncSeriesHook.lazyCompileHook (../wp-react-starter--wp-reactjs-multi-starter-wp-reactjs-starter-1.2.0/node_modules/tapable/lib/Hook.js:154:20)
    at ../wp-react-starter--wp-reactjs-multi-starter-wp-reactjs-starter-1.2.0/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (../wp-react-starter--wp-reactjs-multi-starter-wp-reactjs-starter-1.2.0/node_modules/webpack/lib/Compiler.js:499:39)
    at ../wp-react-starter--wp-reactjs-multi-starter-wp-reactjs-starter-1.2.0/node_modules/webpack/lib/Compiler.js:298:10
    at ../wp-react-starter--wp-reactjs-multi-starter-wp-reactjs-starter-1.2.0/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (../wp-react-starter--wp-reactjs-multi-starter-wp-reactjs-starter-1.2.0/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook (../wp-react-starter--wp-reactjs-multi-starter-wp-reactjs-starter-1.2.0/node_modules/tapable/lib/Hook.js:154:20)
    at ../wp-react-starter--wp-reactjs-multi-starter-wp-reactjs-starter-1.2.0/node_modules/webpack/lib/Compiler.js:482:27
    at ../wp-react-starter--wp-reactjs-multi-starter-wp-reactjs-starter-1.2.0/node_modules/neo-async/async.js:2818:7
    at done (../wp-react-starter--wp-reactjs-multi-starter-wp-reactjs-starter-1.2.0/node_modules/neo-async/async.js:3522:9)

**Comment by honzavaclavik** [comment]
I Have same problem

**Comment by honzavaclavik** [comment]
This patch worked for me... 

Index: plugins/pohoda-connector/src/public/ts/components/todo.tsx
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- plugins/pohoda-connector/src/public/ts/components/todo.tsx	(revision c0dc343597353f82be65a40e10157c13c1b3f17e)
+++ plugins/pohoda-connector/src/public/ts/components/todo.tsx	(revision 99b95378a28022b1d81eb8b21d2682fe790d876d)
@@ -4,6 +4,7 @@
 import { TodoItem } from "./todoItem";
 import { useStores } from "../store";
 import { __ } from "../utils";
+import { TodoModel } from "../models";
 
 /* istanbul ignore next: Example implementations gets deleted the most time after plugin creation! */
 /**
@@ -35,7 +36,7 @@
                 {__("Add")}
             </Button>
             <ul>
-                {todoStore.todos.map((t) => (
+                {todoStore.todos.map((t: TodoModel) => (
                     <TodoItem key={t.id} todo={t} />
                 ))}
                 {!todoStore.todos.length && <li>No entries</li>}
Index: plugins/pohoda-connector/src/public/ts/store/stores.tsx
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- plugins/pohoda-connector/src/public/ts/store/stores.tsx	(revision c0dc343597353f82be65a40e10157c13c1b3f17e)
+++ plugins/pohoda-connector/src/public/ts/store/stores.tsx	(revision 99b95378a28022b1d81eb8b21d2682fe790d876d)
@@ -26,7 +26,7 @@
         useStores: () => RootStore;
     };
 
-    public get context() {
+    public get context(): any {
         return this.contextMemo
             ? this.contextMemo
             : (this.contextMemo = createContextFactory((this as unknown) as RootStore));
@@ -37,7 +37,7 @@
         this.optionStore = new OptionStore(this);
     }
 
-    public static get StoreProvider() {
+    public static get StoreProvider(): any {
         return RootStore.get.context.StoreProvider;
     }
 
Index: plugins/pohoda-connector/src/public/ts/utils/index.tsx
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- plugins/pohoda-connector/src/public/ts/utils/index.tsx	(revision c0dc343597353f82be65a40e10157c13c1b3f17e)
+++ plugins/pohoda-connector/src/public/ts/utils/index.tsx	(revision 99b95378a28022b1d81eb8b21d2682fe790d876d)
@@ -18,7 +18,7 @@
     }
 
     // Create i18n relevant stuff from factory
-    public get localization() {
+    public get localization(): any {
         return this.localizationMemo
             ? this.localizationMemo
             : (this.localizationMemo = createLocalizationFactory(RootStore.get.optionStore.pureSlug));
